=== camenduru/flux.1-dev-distill-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Model: Flux.1 Dev Distill",
      "author": "Black Forest Labs: Andreas Blattmann, Andrew Holmes, Axel Sauer, Dominik Lorenz, Dustin Podell, Frederic Boesel, Harry Saini, Jonas MÃ¼ller, Kyle Lacey, Patrick Esser, Robin Rombach, Sumith Kulal, Tim Dockhorn, Yam Levi, Zion English",
      "page": "https://blackforestlabs.ai/",
      "code": "https://github.com/black-forest-labs/flux",
      "jupyter": "https://github.com/camenduru/flux-jupyter",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/flux.1-dev-distill.ipynb",
      "tags": [
        "Text to Image"
      ],
      "widget": "readme"
    },
    "positive_prompt": {
      "type": "string",
      "description": "Positive Prompt",
      "widget": "textarea"
    },
    "negative_prompt": {
      "type": "string",
      "description": "Negative Prompt",
      "widget": "textarea"
    },
    "enable_custom_lora": {
      "type": "boolean",
      "description": "Enable Custom Lora"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "lora_url",
      "visibleIf": {
        "enable_custom_lora": [
          true
        ]
      }
    },
    "lora_url": {
      "type": "string",
      "description": "Lora URL",
      "widget": "textarea",
      "visibleIf": {
        "enable_custom_lora": [
          true
        ]
      }
    },
    "lora_strength_model": {
      "type": "number",
      "widget": "select",
      "description": "Lora Strength Model",
      "oneOf": [
        {
          "description": "0",
          "enum": [
            0
          ]
        },
        {
          "description": "0.1",
          "enum": [
            0.1
          ]
        },
        {
          "description": "0.2",
          "enum": [
            0.2
          ]
        },
        {
          "description": "0.3",
          "enum": [
            0.3
          ]
        },
        {
          "description": "0.4",
          "enum": [
            0.4
          ]
        },
        {
          "description": "0.5",
          "enum": [
            0.5
          ]
        },
        {
          "description": "0.6",
          "enum": [
            0.6
          ]
        },
        {
          "description": "0.7",
          "enum": [
            0.7
          ]
        },
        {
          "description": "0.8",
          "enum": [
            0.8
          ]
        },
        {
          "description": "0.9",
          "enum": [
            0.9
          ]
        },
        {
          "description": "1",
          "enum": [
            1
          ]
        }
      ],
      "default": 1,
      "visibleIf": {
        "enable_custom_lora": [
          true
        ]
      }
    },
    "lora_strength_clip": {
      "type": "number",
      "widget": "select",
      "description": "Lora Strength Clip",
      "oneOf": [
        {
          "description": "0",
          "enum": [
            0
          ]
        },
        {
          "description": "0.1",
          "enum": [
            0.1
          ]
        },
        {
          "description": "0.2",
          "enum": [
            0.2
          ]
        },
        {
          "description": "0.3",
          "enum": [
            0.3
          ]
        },
        {
          "description": "0.4",
          "enum": [
            0.4
          ]
        },
        {
          "description": "0.5",
          "enum": [
            0.5
          ]
        },
        {
          "description": "0.6",
          "enum": [
            0.6
          ]
        },
        {
          "description": "0.7",
          "enum": [
            0.7
          ]
        },
        {
          "description": "0.8",
          "enum": [
            0.8
          ]
        },
        {
          "description": "0.9",
          "enum": [
            0.9
          ]
        },
        {
          "description": "1",
          "enum": [
            1
          ]
        }
      ],
      "default": 1,
      "visibleIf": {
        "enable_custom_lora": [
          true
        ]
      }
    },
    "seed": {
      "type": "integer",
      "description": "Seed (if 0 random)"
    },
    "steps": {
      "type": "integer",
      "widget": "select",
      "description": "Steps",
      "oneOf": [
        {
          "description": "8",
          "enum": [
            8
          ]
        },
        {
          "description": "10",
          "enum": [
            8
          ]
        },
        {
          "description": "12",
          "enum": [
            16
          ]
        }
      ],
      "default": 20
    },
    "cfg": {
      "type": "number",
      "description": "CFG"
    },
    "sampler_name": {
      "type": "string",
      "widget": "select",
      "description": "Sampler Name",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "heun",
          "enum": [
            "heun"
          ]
        },
        {
          "description": "heunpp2",
          "enum": [
            "heunpp2"
          ]
        },
        {
          "description": "dpm_2",
          "enum": [
            "dpm_2"
          ]
        },
        {
          "description": "lms",
          "enum": [
            "lms"
          ]
        },
        {
          "description": "dpmpp_2m",
          "enum": [
            "dpmpp_2m"
          ]
        },
        {
          "description": "ipndm",
          "enum": [
            "ipndm"
          ]
        },
        {
          "description": "deis",
          "enum": [
            "deis"
          ]
        },
        {
          "description": "ddim",
          "enum": [
            "ddim"
          ]
        },
        {
          "description": "uni_pc",
          "enum": [
            "uni_pc"
          ]
        },
        {
          "description": "uni_pc_bh2",
          "enum": [
            "uni_pc_bh2"
          ]
        }
      ],
      "default": "euler"
    },
    "scheduler": {
      "type": "string",
      "widget": "select",
      "description": "Scheduler",
      "oneOf": [
        {
          "description": "beta",
          "enum": [
            "beta"
          ]
        },
        {
          "description": "normal",
          "enum": [
            "normal"
          ]
        },
        {
          "description": "sgm_uniform",
          "enum": [
            "sgm_uniform"
          ]
        },
        {
          "description": "simple",
          "enum": [
            "simple"
          ]
        },
        {
          "description": "ddim_uniform",
          "enum": [
            "ddim_uniform"
          ]
        }
      ],
      "default": "normal"
    },
    "max_shift": {
      "type": "number",
      "description": "Max Shift"
    },
    "base_shift": {
      "type": "number",
      "description": "Base Shift"
    },
    "width": {
      "type": "integer",
      "description": "Width"
    },
    "height": {
      "type": "integer",
      "description": "Height"
    },
    "example": {
      "type": "string",
      "image1": "https://files.catbox.moe/flxrwn.png",
      "image2": "https://files.catbox.moe/n6fgoc.png",
      "image3": "https://files.catbox.moe/gbjr5b.png",
      "image4": "https://files.catbox.moe/gcxz5n.png",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/flux.1-dev-distill-tost/model.json
{ 
    "positive_prompt": "A photograph captures a curly-haired, light brown dog playfully splashing in the ocean. The dog, with wet fur, is mid-pounce, creating dynamic water splashes around it. The background features a vibrant sunset sky, transitioning from deep blue to soft orange and pink hues. The ocean water is clear and turquoise, adding a serene contrast to the energetic foreground. The image exudes a sense of joy and freedom, with the dog's expressive eyes and open mouth adding to the lively atmosphere.",
    "negative_prompt": "blurry, sharp",
    "enable_custom_lora": false,
    "lora_url": "https://huggingface.co/TostAI/flux-1-dev-lora/resolve/main/8iiu0y.safetensors",
    "lora_strength_model": 1,
    "lora_strength_clip": 1,
    "seed": 0,
    "steps": 8,
    "cfg": 3.5,
    "sampler_name": "euler",
    "scheduler": "beta",
    "max_shift": 1.15,
    "base_shift": 0.50,
    "width": 1024,
    "height": 1024
}
